name: CI

on:
  # Runs on pushes to any branch and all pull requests
  push:
  pull_request:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Cook CLI
        run: |
          curl -sSfL https://github.com/cooklang/CookCLI/releases/latest/download/cook-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv cook /usr/local/bin/
          cook --version

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Lint recipes
        run: just lint

      - name: Verify recipes are in sync
        run: just verify-sync
